spring:
  profiles:
    active: local
---
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: 6lueparr0t
logging:
  level:
    com.rgbplace: TRACE
---
# local 환경
spring:
  profiles: local
  devtools:
    restart:
      enabled: true
      additional-paths: classpath:/
    livereload:
      enabled: true
  redis:
    port: 6379
    host: localhost
    password: ENC(NMrFQLYI3+tSgzx8zdbyx+K5sQzMC2+IIjCfL6p+WOU=)
server:
  port: 8080